### ISSUE TITLE
Problem with write.py and read.py script on Raspberry Pi3B+ 

### ISSUE THREAD

**Issue by priyesh1112** [mxgxw/MFRC522-python#81]

**Comment by priyesh1112** [comment]
Welcome to the MFRC522 data read example
Press Ctrl-C to stop.
Traceback (most recent call last):
  File "rfidreader.py", line 51, in <module>
    (status,TagType) = MIFAREReader.MFRC522_Request(MIFAREReader.PICC_REQIDL)
  File "/home/pi/MFRC522.py", line 239, in MFRC522_Request
    self.Write_MFRC522(self.BitFramingReg, 0x07)
TypeError: Write_MFRC522() takes exactly 2 arguments (3 given)



I would be glad if someone could guide me accordingly. 
Thanks and Regards
