### ISSUE TITLE
Error when running the python Code to read RFID tag

### ISSUE THREAD

**Issue by priyesh1112** [mxgxw/MFRC522-python#82]
Welcome to the MFRC522 data read example
Press Ctrl-C to stop.
Traceback (most recent call last):
  File "Read.py", line 51, in <module>
    (status, TagType) = MIFAREReader.MFRC522_Request(MIFAREReader.PICC_REQIDL)
  File "/home/pi/MFRC522.py", line 243, in MFRC522_Request
    (status, backData, backBits) = self.MFRC522_ToCard(self.PCD_TRANSCEIVE, TagType)
TypeError: 'NoneType' object is not iterable

Could anyone please help in this matter? I am finding it troublesome and so would be glad if someone could sort this issue.

Thanks and Regards

**Comment by exhale9160** [comment]
Hi! I suppose the problem is that the code doesn't want to read a card at all, I think I have a solution for that:

`git clone https://github.com/pimylifeup/MFRC522-python.git`

`cd MFRC522-python`

`sudo python3 setup.py install`

then go back a directory, create a new one, and in there, create a file, for example Read.py, and in it, paste this code:

`from time import sleep
import sys
from mfrc522 import SimpleMFRC522
reader = SimpleMFRC522()

try:
     while True:
            print("Hold a card or tag near the reader")
            id, text = reader.read()
            print("ID: %s\nText: %s" % (id, text))
            sleep(3)
except KeyboardInterrupt:
        GPIO.cleanup()
        raise`
This should work.
